#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#logging:
#  level:
#    org.springframework.boot.actuate: DEBUG
#    org.springframework.test: DEBUG # â‡’ Cachable beans logging

#spring:
#  jackson:
#    default-property-inclusion: NON_NULL

# Swagger-ui custom path (http://localhost:8080/swagger-ui/index.html)
springdoc:
  swagger-ui:
    use-root-path: true
    display-request-duration: true

server:
  error:
    include-binding-errors: always